  - name: criando arquivos com playbook
    hosts: terraform-ansible

    tasks: 
    - name: Instando o python3 & virtualenv
      become: yes
      apt: 
        pkg: 
        - python3
        - virtualenv
        update_cache: yes
    - name: Instalando dependencias pip (Django & Django Rest)
      pip: 
        virtualenv: /home/ubuntu/tcc/venv
        name: 
          - django
          - djangorestframework
    - name: Iniciando o projeto 
      shell: '. /home/ubuntu/tcc/venv/bin/activate; django-admin startproject setup /home/ubuntu/tcc/'
    - name: Alteração de hosts do settings
      lineinfile: 
        path: /home/ubuntu/tcc/setup/settings.py
        regexp: 'ALLOWED_HOSTS'
        line: 'ALLOWED_HOSTS = ["*"]'
        backrefs: yes
        