  - name: criando arquivos com playbook
    hosts: terraform-ansible

    tasks: 
      - name: criando o arquivo 
        copy:
          dest: /home/ubuntu/index.html
          content: <h1>ISSO E MUITO LEGAL</h1>
      - name: criando servidor web
        shell: "nohup busybox httpd -f -p 8080 &"