  - name: criando arquivos com playbook
    hosts: terraform-ansible

    tasks: 
    - name: Instando o python3 & virtualenv
      become: yes
      apt: 
        pkg: 
        - python3
        - virtualenv
        update_cache: yes
    - name: Instalando dependencias pip (Django & Django Rest)
      pip: 
        virtualenv: /home/ubuntu/tcc/venv
        name: 
          - django
          - djangorestframework
        